#!/bin/bash
# Camera Driver Installation Script for Raspberry Pi Cameras
# Supports Pi Camera v3, Global Shutter, AI Camera, and USB cameras

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
ROS_DISTRO="jazzy"

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

detect_platform() {
    if [[ $(uname -m) == "aarch64" ]]; then
        log_info "Detected ARM64 (Raspberry Pi)"
        return 0
    else
        log_info "Detected x86/AMD64 (Desktop/Other)"
        return 1
    fi
}

install_pi_camera_v3() {
    log_info "Installing Raspberry Pi Camera v3 support..."

    sudo apt update
    sudo apt install -y \
        python3-libcamera \
        python3-picamera2 \
        python3-kms++ \
        libcap-dev \
        libjpeg-dev \
        libtiff-dev

    # Test camera
    log_info "Testing camera..."
    if libcamera-hello --list-cameras 2>/dev/null | grep -q "Available"; then
        log_success "Pi Camera v3 detected and working"

        # Capture test image
        libcamera-jpeg -o /tmp/camera_test.jpg --width 1280 --height 720
        if [[ -f "/tmp/camera_test.jpg" ]]; then
            log_success "Test image captured successfully"
            rm /tmp/camera_test.jpg
        fi
    else
        log_error "Pi Camera v3 not detected"
        return 1
    fi
}

install_global_shutter() {
    log_info "Installing Raspberry Pi Global Shutter Camera support..."

    # Same as Pi Camera v3, but verify global shutter mode
    install_pi_camera_v3

    # Verify global shutter capabilities
    log_info "Verifying global shutter mode..."
    v4l2-ctl -d /dev/video0 --all 2>/dev/null | grep -q "global shutter" && \
        log_success "Global shutter mode confirmed" || \
        log_warning "Global shutter mode not confirmed (may still work)"
}

install_ai_camera() {
    log_info "Installing Raspberry Pi AI Camera support..."

    # Install base camera support
    install_pi_camera_v3

    # Install AI-specific packages
    sudo apt install -y python3-hailo || log_warning "Hailo AI package not available"

    # Install TensorFlow Lite runtime
    pip3 install --break-system-packages \
        tflite-runtime \
        pillow \
        numpy

    # Test AI camera
    log_info "Testing AI Camera..."
    python3 -c "
import picamera2
try:
    cam = picamera2.Picamera2()
    config = cam.create_preview_configuration(main={'size': (640, 480)})
    cam.configure(config)
    cam.start()
    cam.stop()
    print('AI Camera working')
except Exception as e:
    print(f'AI Camera test failed: {e}')
    exit(1)
" && log_success "AI Camera working" || log_error "AI Camera not working"
}

install_usb_camera() {
    log_info "Installing USB Camera support..."

    sudo apt update
    sudo apt install -y \
        v4l-utils \
        ros-$ROS_DISTRO-usb-cam \
        guvcview || log_warning "guvcview not available"

    # List available cameras
    log_info "Available cameras:"
    v4l2-ctl --list-devices

    # Test first USB camera
    if [[ -e "/dev/video0" ]]; then
        log_info "Testing USB camera..."
        v4l2-ctl -d /dev/video0 --all | head -20

        # Try to capture test image
        timeout 5 v4l2-ctl -d /dev/video0 --set-fmt-video=width=640,height=480,pixelformat=YUYV \
            --stream-mmap --stream-to=/tmp/usb_test.raw --stream-count=1 2>/dev/null && \
            log_success "USB camera test successful" || \
            log_warning "USB camera test inconclusive (may still work)"
    else
        log_warning "No USB camera devices found"
    fi
}

test_ros_camera_bridge() {
    log_info "Testing ROS camera bridge..."

    # Test if ROS is available
    if ! command -v ros2 >/dev/null 2>&1; then
        log_warning "ROS 2 not found, skipping ROS camera tests"
        return 0
    fi

    # Source ROS
    source /opt/ros/$ROS_DISTRO/setup.bash 2>/dev/null || true

    # Test image transport
    python3 -c "
import rclpy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2
import numpy as np

rclpy.init()
bridge = CvBridge()

# Create test image
test_img = np.random.randint(0, 255, (480, 640, 3), dtype=np.uint8)
ros_img = bridge.cv2_to_imgmsg(test_img, 'bgr8')

print('ROS camera bridge working')
rclpy.shutdown()
" && log_success "ROS camera bridge working" || log_error "ROS camera bridge failed"
}

create_camera_config() {
    log_info "Creating camera configuration..."

    # Create config directory if it doesn't exist
    mkdir -p config

    # Camera calibration template
    cat > config/camera_calibration.yaml << EOF
# Camera-LiDAR Calibration Parameters
# Generated by calibration.py

camera_matrix:
  rows: 3
  cols: 3
  data: [800.0, 0.0, 640.0, 0.0, 800.0, 360.0, 0.0, 0.0, 1.0]

distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]

extrinsic_rotation: [0.0, 0.0, 0.0]  # roll, pitch, yaw in degrees
extrinsic_translation: [0.0, 0.0, 0.0]  # x, y, z in meters

# Camera-specific settings
camera_type: "picamera"  # picamera, usb, or arducam
resolution: [1280, 720]
fps: 30
auto_exposure: true
awb_mode: "auto"  # auto, daylight, cloudy, etc.
EOF

    log_success "Camera configuration created at config/camera_calibration.yaml"
}

main() {
    echo "======================================="
    echo "LiDAR-Camera Fusion Camera Setup"
    echo "======================================="

    if [[ $# -eq 0 ]]; then
        echo "Usage: $0 <camera_type>"
        echo "Available camera types:"
        echo "  picamera    - Raspberry Pi Camera v3"
        echo "  global      - Raspberry Pi Global Shutter Camera"
        echo "  ai          - Raspberry Pi AI Camera"
        echo "  usb         - USB Camera"
        echo "  all         - Install all camera types"
        exit 1
    fi

    camera_type="$1"

    case "$camera_type" in
        "picamera")
            install_pi_camera_v3
            ;;
        "global")
            install_global_shutter
            ;;
        "ai")
            install_ai_camera
            ;;
        "usb")
            install_usb_camera
            ;;
        "all")
            log_info "Installing all camera types..."
            install_pi_camera_v3
            install_global_shutter
            install_ai_camera
            install_usb_camera
            ;;
        *)
            log_error "Unknown camera type: $camera_type"
            exit 1
            ;;
    esac

    # Test ROS integration
    test_ros_camera_bridge

    # Create configuration
    create_camera_config

    log_success "Camera setup complete!"
    echo ""
    echo "Next steps:"
    echo "1. Connect your camera hardware"
    echo "2. Run calibration: python3 src/core/calibration.py"
    echo "3. Test fusion: python3 src/core/fusion.py"
}

main "$@"
